/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_exobel_routerkeygen_algorithms_UpcKeygen */

#ifndef _Included_org_exobel_routerkeygen_algorithms_UpcKeygen
#define _Included_org_exobel_routerkeygen_algorithms_UpcKeygen
#ifdef __cplusplus
extern "C" {
#endif
#undef org_exobel_routerkeygen_algorithms_UpcKeygen_SUPPORTED
#define org_exobel_routerkeygen_algorithms_UpcKeygen_SUPPORTED 2L
#undef org_exobel_routerkeygen_algorithms_UpcKeygen_UNLIKELY_SUPPORTED
#define org_exobel_routerkeygen_algorithms_UpcKeygen_UNLIKELY_SUPPORTED 1L
#undef org_exobel_routerkeygen_algorithms_UpcKeygen_UNSUPPORTED
#define org_exobel_routerkeygen_algorithms_UpcKeygen_UNSUPPORTED 0L
/*
 * Class:     org_exobel_routerkeygen_algorithms_UpcKeygen
 * Method:    upcNative
 * Signature: ([B[BI)[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_org_exobel_routerkeygen_algorithms_UpcKeygen_upcNative
        (JNIEnv *, jobject, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
