.\" Copyright (C) 2010-13 RouterKeygen
.\" Author: Rui Araújo <ruka.araujo@gmail.com>
.\"
.\" This is free software; you may redistribute it and/or modify
.\" it under the terms of the GNU General Public License as
.\" published by the Free Software Foundation; either version 2,
.\" or (at your option) any later version.
.\"
.\" This is distributed in the hope that it will be useful, but
.\" WITHOUT ANY WARRANTY; without even the implied warranty of
.\" MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
.\" GNU General Public License for more details.
.\"
.\" You should have received a copy of the GNU General Public License 
.\" along with this; if not write to the Free Software Foundation, Inc.
.\" 59 Temple Place, Suite 330, Boston, MA 02111-1307  USA
.TH RouterKeygen 1 "Mar 31, 2013"
.SH NAME
routerkeygen \- RouterKeygen
.SH SYNOPSIS
.B routerkeygen
.RI [ OPTIONS ]...
.RI [ filename|URI ]...
.SH DESCRIPTION
Put your bla bla here
.SH OPTIONS
.TP
.B \-\-help|-?
Outputs help.
.TP
.B \-\-version
Outputs version information and exits.
.SH BUGS
If you find a bug, please report it to ruka.araujo@gmail.com
.PP
.SH AUTHOR
This manual page was written by Rui Araújo <ruka.araujo@gmail.com>, for the Debian
GNU/Linux system (but may be used by others).
